server:
  port: 8082
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/profile-service
    username: root
    password: 2to6n10pm
    driver-class-name: com.mysql.cj.jdbc.Driver
